name = "q-ots-website"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "qots-db"
database_id = "0b3fdbe3-18aa-483c-86cf-8936334d6e83"

[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"  # Optional: Create KV namespace if needed
